# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\aboutcscan.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowCscan(object):
    def setupUi(self, MainWindowCscan):
        MainWindowCscan.setObjectName("MainWindowCscan")
        MainWindowCscan.resize(1230, 760)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindowCscan.sizePolicy().hasHeightForWidth())
        MainWindowCscan.setSizePolicy(sizePolicy)
        MainWindowCscan.setMinimumSize(QtCore.QSize(1230, 760))
        MainWindowCscan.setMaximumSize(QtCore.QSize(1230, 760))
        MainWindowCscan.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindowCscan)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(0, -20, 1231, 781))
        self.textBrowser.setObjectName("textBrowser")
        MainWindowCscan.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindowCscan)
        QtCore.QMetaObject.connectSlotsByName(MainWindowCscan)

    def retranslateUi(self, MainWindowCscan):
        _translate = QtCore.QCoreApplication.translate
        MainWindowCscan.setWindowTitle(_translate("MainWindowCscan", "MainWindow"))
        self.textBrowser.setHtml(_translate("MainWindowCscan", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'MS Shell Dlg 2\',\'sans-serif\'; font-size:16pt; font-weight:600; text-decoration: underline; color:#40424e;\">CSCAN</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'MS Shell Dlg 2\',\'sans-serif\'; font-size:13pt; color:#40424e;\">In SCAN algorithm, the disk arm again scans the path that has been scanned, after reversing its direction. So, it may be possible that too many requests are waiting at the other end or there may be zero or few requests pending at the scanned area.These situations are avoided in the CSCAN</span><span style=\" font-family:\'MS Shell Dlg 2\',\'sans-serif\'; font-size:13pt; font-style:italic; color:#40424e;\"> </span><span style=\" font-family:\'MS Shell Dlg 2\',\'sans-serif\'; font-size:13pt; color:#40424e;\">algorithm in which the disk arm instead of reversing its direction goes to the other end of the disk and starts servicing the requests from there. So, the disk arm moves in a circular fashion and this algorithm is also similar to the SCAN algorithm and hence it is known as C-SCAN (Circular SCAN).</span><span style=\" font-family:\'MS Shell Dlg 2\',\'sans-serif\'; font-size:8pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'MS Shell Dlg 2\',\'sans-serif\'; font-size:14pt; font-weight:600; color:#40424e;\">Algorithm</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'MS Shell Dlg 2\',\'sans-serif\'; font-size:13pt; color:#40424e;\">●</span><span style=\" font-family:\'Times New Roman\',\'serif\'; font-size:7pt; color:#40424e;\">      </span><span style=\" font-family:\'MS Shell Dlg 2\',\'sans-serif\'; font-size:13pt; color:#40424e;\">Let Request array represents an array storing indexes of tracks that have been requested in ascending order of their time of arrival. ‘Head’ is the position of disk head.</span><span style=\" font-family:\'MS Shell Dlg 2\',\'sans-serif\'; font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'MS Shell Dlg 2\',\'sans-serif\'; font-size:13pt; color:#40424e;\">●</span><span style=\" font-family:\'Times New Roman\',\'serif\'; font-size:7pt; color:#40424e;\">      </span><span style=\" font-family:\'MS Shell Dlg 2\',\'sans-serif\'; font-size:13pt; color:#40424e;\">The head services only in the right direction from 0 to size of the disk.</span><span style=\" font-family:\'MS Shell Dlg 2\',\'sans-serif\'; font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'MS Shell Dlg 2\',\'sans-serif\'; font-size:13pt; color:#40424e;\">●</span><span style=\" font-family:\'Times New Roman\',\'serif\'; font-size:7pt; color:#40424e;\">      </span><span style=\" font-family:\'MS Shell Dlg 2\',\'sans-serif\'; font-size:13pt; color:#40424e;\">While moving in the left direction do not service any of the tracks.</span><span style=\" font-family:\'MS Shell Dlg 2\',\'sans-serif\'; font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'MS Shell Dlg 2\',\'sans-serif\'; font-size:13pt; color:#40424e;\">●</span><span style=\" font-family:\'Times New Roman\',\'serif\'; font-size:7pt; color:#40424e;\">      </span><span style=\" font-family:\'MS Shell Dlg 2\',\'sans-serif\'; font-size:13pt; color:#40424e;\">When we reach at the beginning (left end) reverse the direction.</span><span style=\" font-family:\'MS Shell Dlg 2\',\'sans-serif\'; font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'MS Shell Dlg 2\',\'sans-serif\'; font-size:13pt; color:#40424e;\">●</span><span style=\" font-family:\'Times New Roman\',\'serif\'; font-size:7pt; color:#40424e;\">      </span><span style=\" font-family:\'MS Shell Dlg 2\',\'sans-serif\'; font-size:13pt; color:#40424e;\">While moving in the right direction it services all tracks one by one.</span><span style=\" font-family:\'MS Shell Dlg 2\',\'sans-serif\'; font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'MS Shell Dlg 2\',\'sans-serif\'; font-size:13pt; color:#40424e;\">●</span><span style=\" font-family:\'Times New Roman\',\'serif\'; font-size:7pt; color:#40424e;\">      </span><span style=\" font-family:\'MS Shell Dlg 2\',\'sans-serif\'; font-size:13pt; color:#40424e;\">While moving in the right direction, calculate the absolute distance of the track from the head.</span><span style=\" font-family:\'MS Shell Dlg 2\',\'sans-serif\'; font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'MS Shell Dlg 2\',\'sans-serif\'; font-size:13pt; color:#40424e;\">●</span><span style=\" font-family:\'Times New Roman\',\'serif\'; font-size:7pt; color:#40424e;\">      </span><span style=\" font-family:\'MS Shell Dlg 2\',\'sans-serif\'; font-size:13pt; color:#40424e;\">Increment the total seek count with this distance.</span><span style=\" font-family:\'MS Shell Dlg 2\',\'sans-serif\'; font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'MS Shell Dlg 2\',\'sans-serif\'; font-size:13pt; color:#40424e;\">●</span><span style=\" font-family:\'Times New Roman\',\'serif\'; font-size:7pt; color:#40424e;\">      </span><span style=\" font-family:\'MS Shell Dlg 2\',\'sans-serif\'; font-size:13pt; color:#40424e;\">Currently serviced track position now becomes the new head position.</span><span style=\" font-family:\'MS Shell Dlg 2\',\'sans-serif\'; font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'MS Shell Dlg 2\',\'sans-serif\'; font-size:13pt; color:#40424e;\">●</span><span style=\" font-family:\'Times New Roman\',\'serif\'; font-size:7pt; color:#40424e;\">      </span><span style=\" font-family:\'MS Shell Dlg 2\',\'sans-serif\'; font-size:13pt; color:#40424e;\">Go to step 6 until we reach the right end of the disk.</span><span style=\" font-family:\'MS Shell Dlg 2\',\'sans-serif\'; font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'MS Shell Dlg 2\',\'sans-serif\'; font-size:13pt; color:#40424e;\">●</span><span style=\" font-family:\'Times New Roman\',\'serif\'; font-size:7pt; color:#40424e;\">      </span><span style=\" font-family:\'MS Shell Dlg 2\',\'sans-serif\'; font-size:13pt; color:#40424e;\">If we reach at the right end of the disk reverse the direction and go to step 3 until all tracks in the request array have not been serviced.</span><span style=\" font-family:\'MS Shell Dlg 2\',\'sans-serif\'; font-size:8pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'MS Shell Dlg 2\',\'sans-serif\'; font-size:12pt; font-weight:600; color:#40424e;\">Advantages</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'MS Shell Dlg 2\',\'sans-serif\'; font-size:13pt; color:#40424e;\">●</span><span style=\" font-family:\'Times New Roman\',\'serif\'; font-size:7pt; color:#40424e;\">      </span><span style=\" font-family:\'MS Shell Dlg 2\',\'sans-serif\'; font-size:13pt; color:#40424e;\">Provides more uniform wait time compared to SCAN</span><span style=\" font-size:8pt;\"> </span></p></body></html>"))
