# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\warningGraph.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowGraphWarn(object):
    def setupUi(self, MainWindowGraphWarn):
        MainWindowGraphWarn.setObjectName("MainWindowGraphWarn")
        MainWindowGraphWarn.resize(468, 224)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindowGraphWarn.sizePolicy().hasHeightForWidth())
        MainWindowGraphWarn.setSizePolicy(sizePolicy)
        MainWindowGraphWarn.setMinimumSize(QtCore.QSize(468, 224))
        MainWindowGraphWarn.setMaximumSize(QtCore.QSize(468, 224))
        self.centralwidget = QtWidgets.QWidget(MainWindowGraphWarn)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 30, 301, 141))
        self.label.setObjectName("label")
        self.ButtonWarnGraph = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonWarnGraph.setGeometry(QtCore.QRect(190, 180, 93, 28))
        self.ButtonWarnGraph.setObjectName("ButtonWarnGraph")
        MainWindowGraphWarn.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindowGraphWarn)
        QtCore.QMetaObject.connectSlotsByName(MainWindowGraphWarn)

    def retranslateUi(self, MainWindowGraphWarn):
        _translate = QtCore.QCoreApplication.translate
        MainWindowGraphWarn.setWindowTitle(_translate("MainWindowGraphWarn", "MainWindow"))
        self.label.setText(_translate("MainWindowGraphWarn", "<html><head/><body><p><span style=\" font-size:12pt;\">Tracks should be between 0-199.</span></p><p><br/></p><p><span style=\" font-size:12pt;\">Please check the entries !!</span></p></body></html>"))
        self.ButtonWarnGraph.setText(_translate("MainWindowGraphWarn", "OK"))
