# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\warning.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogWarning(object):
    def setupUi(self, DialogWarning):
        DialogWarning.setObjectName("DialogWarning")
        DialogWarning.resize(383, 201)
        self.label = QtWidgets.QLabel(DialogWarning)
        self.label.setGeometry(QtCore.QRect(70, 20, 251, 111))
        self.label.setObjectName("label")

        self.retranslateUi(DialogWarning)
        QtCore.QMetaObject.connectSlotsByName(DialogWarning)

    def retranslateUi(self, DialogWarning):
        _translate = QtCore.QCoreApplication.translate
        DialogWarning.setWindowTitle(_translate("DialogWarning", "Dialog"))
        self.label.setText(_translate("DialogWarning", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">No Algorithm selected !!</span></p><p align=\"center\"><br/></p><p align=\"center\"><span style=\" font-size:12pt;\">Please select the algorithm.</span></p></body></html>"))
